package pw.yumc.BukkitInjectedTools;

import org.bukkit.Bukkit;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;

import pw.yumc.BukkitInjectedTools.event.YumTestEvent;
import pw.yumc.YumCore.bukkit.P;

/**
 * Yum监听
 *
 * @since 2016年7月18日 下午7:06:20
 * @author 喵♂呜
 */
public class YumTestListener implements Listener {
    public YumTestListener() {
        Bukkit.getPluginManager().registerEvents(this, P.instance);
    }

    @EventHandler
    public void onTest(final YumTestEvent e) {
        throw new IllegalArgumentException("Yum事件监控测试!");
    }
}
